### ISSUE TITLE
Rex5?

### ISSUE THREAD

**Issue by olien** [skerbis/redaxo_piwik_tracker-rex4#8]
Hi Thomas,

hast du vor das Addon REX5 kompatibel zu machen?
(Ansonsten würde ich mir das evtl. mal angucken.)

LG
Oliver

**Comment by skerbis** [comment]
Gerne, leg los. Schau mal in die Branches

**Comment by olien** [comment]
Wandert dann wahrscheinlich hier hin und @phoebusryan übernimmt das:  

https://github.com/phoebusryan/rex_analytics/issues/5

**Comment by skerbis** [comment]
hmm.... was mache ich nun damit?

**Comment by schuer** [comment]
Ich würde das R4 zu FOR werfen.

Was R5 betrifft: Eine Migration wäre nicht allzu aufwendig, allerdings hat mich bei dem Addon konzeptionell immer gestört, dass die Piwik-Daten nicht dynamisch nachgeladen werden, sondern direkt beim Seitenaufruf mitkommen und damit die Seite für einige Zeit blockieren. »Für einige Zeit« können durchaus mal 10-20 Sekunden sein, weil Piwik für den Tracker viele Zahlen aufbereiten muss.

Wir hatten mal ein Caching implementiert, aber das Grundproblem löst das natürlich nicht. Mich persönlich stört es so sehr, dass ich das Plugin nicht in aktueller Form für R5 migrieren würde, sondern mindestens das dynamische Laden einbauen würde. Und wenn man schon dabei ist, könnte man natürlich die Charts moderner ausrauhen. Und bei der Gelegenheit… — du merkst, wo es hingeht ;)

**Comment by skerbis** [comment]
@schuer möchtest Du es nach FOR "forken"? Ist ja ursprünglich Dein Baby.

**Comment by schuer** [comment]
Nein, ist dein Baby. Geschenkt ist geschenkt, wiederholen ist gestohlen ;)

Im Ernst: Ich habe aktuell leider keine Ambitionen, aktiv daran zu entwickeln. Deshalb: Mach du es so, wie du es für richtig hälst.

**Comment by skerbis** [comment]
Alles klar ;-) Wird aber dauern. Ich denke nicht, dass es Sinn macht das 4er Addon nach FOR zu schieben, daher werde ich mich an einem 5er versuchen ;-)

**Comment by skerbis** [comment]
Eine R5 wird es nicht geben
